name: "Setup Testing Environment"
description: "Setup testing environment with specified python version"
author: "gitdev@lrm.photo"

inputs:
  python-version:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Python Version ${{ inputs.python-version }}
      # hacky way to change the python version by temporariliy editing the environment file
      run: |
        sed -i -E 's/(python=)(.*)/\1'${{ inputs.python-version }}'/' ./environment_cpu.yaml
        cat environment_cpu.yaml | grep python

    # overwrites the python version in the environment
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channel-priority: strict
        activate-environment: decode_dev_cpu
        environment-file: environment_cpu.yaml

    - name: Install backport of importlib_resources  # only needed for python 3.6
      run: |
        conda install -y importlib_resources
      if: inputs.python-version <= '3.6'
