name: Build DECODE and upload to Anaconda Cloud


# this will be on release at some point
on: [push]

jobs:
  # this is a pure Python noarch build; we use Linux for convenience
  build-linux:
    runs-on: ubuntu-latest

    env: 
        FILENAMES: temp-filenames.txt

    steps:
    - uses: actions/checkout@v2
    - name: Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install conda build libraries
      run: |
        $CONDA/bin/conda install conda-build anaconda-client

    # build, then also store the file paths that were built    
    - name: Build DECODE
      run: |
        cd ./conda
        $CONDA/bin/conda-build -c turagalab -c pytorch -c conda-forge decode
        $CONDA/bin/conda-build -c turagalab -c pytorch -c conda-forge decode --output > $FILENAMES

    # upload to Anaconda Cloud; keep step separate to minimize exposure of the token
    - name: Upload to Anaconda Cloud
      env:
        ANACONDA_TOKEN: ${{ secrets.TURAGALAB_ANACONDA_TOKEN }}
      run: |
        cd ./conda
        while read PATH; do 
          echo pretend anaconda upload -t token $PATH
        done < $FILENAMES
        