name: Test Example Packages

on:
  push:
  pull_request:
#  schedule:
#    - cron:  '0 8 * * *' # once a day at 8 @ master branch

jobs:
  test_asset_web_availablity:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: decode_dev_cpu
          environment-file: environment_cpu.yaml

      # Run the specific test
      - shell: bash -l {0}
        run: |
          pytest decode/test/test_assets_web.py

      - name: Raise issue when test failed
        if: failure()
        uses: lowply/issue-from-template@v0.1.2
        with:
          IFT_TEMPLATE_NAME: web_availability.md

      - name: keep only max 1 of the automatic issues
        uses: lowply/auto-closer@0.0.3
        with:
          AC_LABEL: auto_web
          AC_KEEP: 1
