name: Unit Tests Future

on:
  push:
  pull_request:

jobs:
  unit_test_future:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set Python Version ${{ matrix.python-version }}
        # hacky way to change the python version by temporariliy editing the environment file
        run: |
          sed -i -E 's/(python=)(.*)/\1'${{ matrix.python-version }}'/' ./environment_cpu.yaml
          cat environment_cpu.yaml | grep python

      - uses: conda-incubator/setup-miniconda@v2
        with:
          channel-priority: strict
          activate-environment: decode_dev_cpu
          environment-file: environment_cpu.yaml

      - name: Run pytest (without big web and graphical output)
        run: |
          pytest -m "not (webbig or plot)" decode/test