name: Unit Tests (Future)

on:
  push:
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up test environment
        uses: ./.github/actions/setup_test_env
        with:
          python-version: ${{ matrix.python-version }}

      # Run the specific test
      - name: Run pytest (without big web and graphical output)
        run: |
          pytest -m "not (webbig or plot)" decode/test
